export default [
  {
    title: 'Guava Gold',
    style: 'Fruited Blonde',
    titleColor: '#fc5',
    price: 6,
    size: '16oz',
    price10oz: 0,
    price12oz: 5,
    price16oz: 6,
    priceCrowler: 12,
    priceGrowler: 19,
    colorLight: '#fc5',
    colorDark: '#f80',
    abv: 4.5
  },{
    title: 'Papaya Don’t Preach',
    titleColor: '#ff5',
    style: 'Fruited American IPA',
    price: 6,
    size: '16oz',
    price10oz: 0,
    price12oz: 6,
    price16oz: 7,
    priceCrowler: 14,
    priceGrowler: 20,
    colorLight: '#ff5',
    colorDark: '#fa0',
    abv: 6.5
  },{
    title: 'TLH',
    titleColor: '#ffc',
    style: 'American Blonde Ale',
    description: '',
    price: 5,
    size: '16oz',
    price10oz: 0,
    price12oz: 4,
    price16oz: 5,
    priceCrowler: 10,
    priceGrowler: 22,
    colorLight: '#ff5',
    colorDark: '#fc5',
    abv: 5
  },{
    title: 'Advanced Darkness',
    titleColor: '#e4a',
    style: 'Robust porter w/coffee & chocolate',
    description: '',
    price: 6,
    size: '16oz',
    price10oz: 0,
    price12oz: 5,
    price16oz: 6,
    priceCrowler: 12,
    priceGrowler: 19,
    colorLight: '#420',
    colorDark: '#2d0a00',
    abv: 6.6
  },{
    title: 'SESH',
    titleColor: '#fff',
    style: 'Session IPA',
    description: '',
    price: 6,
    size: '16oz',
    price10oz: 0,
    price12oz: 5,
    price16oz: 6,
    priceCrowler: 12,
    priceGrowler: 19,
    colorLight: '#f50',
    colorDark: '#c30',
    abv: 4.7
  },{
    title: 'LeBron Jams',
    titleColor: '#fff',
    style: 'Florida-style Berliner Weiss',
    description: '',
    price: 6,
    size: '12oz',
    price10oz: 0,
    price12oz: 6,
    price16oz: 0,
    priceCrowler: 14,
    priceGrowler: 0,
    colorLight: '#ff5',
    colorDark: '#fc5',
    abv: 3.7
  },{
    title: 'Firedrake Märzen',
    titleColor: '#fff',
    style: 'Crisp, amber German lager',
    description: '',
    price: 6,
    size: '16oz',
    price10oz: 0,
    price12oz: 5,
    price16oz: 6,
    priceCrowler: 12,
    priceGrowler: 19,
    colorLight: '#b60',
    colorDark: '#940',
    abv: 5.9
  },{
    title: 'Donut Disco',
    titleColor: '#fff',
    font: 'Fredoka One',
    style: 'Imperial Stout w/cinnamon, coconut, vanilla',
    description: '',
    price: 8,
    size: '10oz',
    price10oz: 8,
    price12oz: 0,
    price16oz: 0,
    priceCrowler: 20,
    priceGrowler: 0,
    colorLight: '#210',
    colorDark: '#100',
    abv: 10.2
  },{
    title: 'Resilience',
    titleColor: '#fff',
    style: 'Piney IPA - Sierra Nevada Collab',
    description: '',
    price: 6,
    size: '16oz',
    price10oz: 0,
    price12oz: 5,
    price16oz: 6,
    priceCrowler: 12,
    priceGrowler: 19,
    colorLight: '#f50',
    colorDark: '#c30',
    abv: 6.7
  },{
    title: 'Blonde Claude Van Damme',
    titleColor: '#fff',
    style: 'Belgian Blonde w/citrus & clove',
    description: '',
    price: 6,
    size: '16oz',
    price10oz: 0,
    price12oz: 5,
    price16oz: 6,
    priceCrowler: 12,
    priceGrowler: 19,
    colorLight: '#ff5',
    colorDark: '#fc5',
    abv: 6.9
  },{
    title: 'BOOMTOWN!',
    titleColor: '#4f4',
    style: 'Gose w/DILL PICKLES',
    description: '',
    price: 6,
    size: '12oz',
    price10oz: 0,
    price12oz: 6,
    price16oz: 0,
    priceCrowler: 14,
    priceGrowler: 0,
    colorLight: '#af0',
    colorDark: '#ff5',
    abv: 3.8
  },{
    title: 'SPACE RAPTOR: Hop Ascension',
    titleColor: '#fff',
    style: 'New England-style IPA',
    description: '',
    price: 6,
    size: '16oz',
    price10oz: 0,
    price12oz: 6,
    price16oz: 7,
    priceCrowler: 14,
    priceGrowler: 22,
    colorLight: '#420',
    colorDark: '#2d0a00',
    abv: 7.5
  }
]