export default [
  {
    title: 'Guava Gold',
    style: 'Guava Puree-infused Blonde',
    titleColor: '#4f4',
    price: 6,
    size: '16oz',
    price10oz: 0,
    price12oz: 5,
    price16oz: 6,
    priceCrowler: 12,
    priceGrowler: 19,
    colorLight: '#fc5',
    colorDark: '#f80',
    abv: 4.5
  },{
    title: 'Hopline Bling!',
    titleColor: '#4f4',
    style: 'Juicy IPA that "can only mean one thing"',
    price: 6,
    size: '16oz',
    price10oz: 0,
    price12oz: 6,
    price16oz: 7,
    priceCrowler: 14,
    priceGrowler: 20,
    colorLight: '#ff5',
    colorDark: '#fa0',
    abv: 7
  },{
    title: 'TLH',
    titleColor: '#4f4',
    style: 'Tallahassee Callsign Blonde Ale',
    description: '',
    price: 5,
    size: '16oz',
    price10oz: 0,
    price12oz: 4,
    price16oz: 5,
    priceCrowler: 10,
    priceGrowler: 22,
    colorLight: '#ff5',
    colorDark: '#fc5',
    abv: 5
  },{
    title: 'Advanced Darkness',
    titleColor: '#4f4',
    style: '2017 Gold Medal Robust Porter',
    description: '',
    price: 6,
    size: '16oz',
    price10oz: 0,
    price12oz: 5,
    price16oz: 6,
    priceCrowler: 12,
    priceGrowler: 19,
    colorLight: '#420',
    colorDark: '#2d0a00',
    abv: 6.6
  },{
    title: 'SESH',
    titleColor: '#fff',
    style: 'Citrus-forward Session IPA',
    description: '',
    price: 6,
    size: '16oz',
    price10oz: 0,
    price12oz: 5,
    price16oz: 6,
    priceCrowler: 12,
    priceGrowler: 19,
    colorLight: '#FACC2E',
    colorDark: '#FFBF00',
    abv: 4.7
  },{
    title: 'LeBron JamZ',
    titleColor: '#fff',
    style: 'Blackberry/Raspberry-infused Sour',
    description: '',
    price: 6,
    size: '12oz',
    price10oz: 0,
    price12oz: 6,
    price16oz: 0,
    priceCrowler: 14,
    priceGrowler: 0,
    colorLight: '#FF0080',
    colorDark: '#FE2E9A',
    abv: 3.8
  },{
    title: 'Firedrake',
    titleColor: '#fff',
    style: 'Crisp, Amber German-style Lager',
    description: '',
    price: 6,
    size: '16oz',
    price10oz: 0,
    price12oz: 5,
    price16oz: 6,
    priceCrowler: 12,
    priceGrowler: 19,
    colorLight: '#b60',
    colorDark: '#940',
    abv: 5.9
  },{
    title: 'Donut Disco',
    titleColor: '#fff',
    style: '(Donut Kingdom) Collab Stout w/cinnamon, coconut & vanilla',
    description: '',
    price: 8,
    size: '10oz',
    price10oz: 8,
    price12oz: 0,
    price16oz: 0,
    priceCrowler: 20,
    priceGrowler: 0,
    colorLight: '#210',
    colorDark: '#100',
    abv: 10.2
  },{
    title: 'Resilience',
    titleColor: '#fff',
    style: '(Sierra Nevada Brewing) Collab IPA',
    description: '',
    price: 6,
    size: '16oz',
    price10oz: 0,
    price12oz: 5,
    price16oz: 6,
    priceCrowler: 12,
    priceGrowler: 19,
    colorLight: '#f50',
    colorDark: '#c30',
    abv: 6.7
  },{
    title: 'BOOMTOWN!',
    titleColor: '#fff',
    style: '2016 Gold Medal Gose w/DILL PICKLES',
    description: '',
    price: 6,
    size: '12oz',
    price10oz: 0,
    price12oz: 6,
    price16oz: 0,
    priceCrowler: 14,
    priceGrowler: 0,
    colorLight: '#af0',
    colorDark: '#ff5',
    abv: 3.8
    },{
    title: '152 Mile Friendship',
    titleColor: '#fff',
    style: '(Cypress & Grove) Collab Tangerine Belgian Blonde',
    description: '',
    price: 6,
    size: '16oz',
    price10oz: 0,
    price12oz: 5,
    price16oz: 6,
    priceCrowler: 12,
    priceGrowler: 19,
    colorLight: '#DF7401',
    colorDark: '#FF4000',
    abv: 6.1
  },{
    title: 'SPACE RAPTOR: Hop Ascension',
    titleColor: '#fff',
    style: '(Hourglass Brewing) Collab Hazy IPA',
    description: '',
    price: 7,
    size: '16oz',
    price10oz: 0,
    price12oz: 6,
    price16oz: 7,
    priceCrowler: 14,
    priceGrowler: 22,
    colorLight: '#FACC2E',
    colorDark: '#FFBF00',
    abv: 7.5
  }
]
