export default [
  {
    title: 'Hopline Bling!',
    titleColor: '#4f4',
    style: 'Juicy IPA that "can only mean one thing"',
    price: 6,
    size: '16oz',
    price10oz: 0,
    price12oz: 6,
    price16oz: 7,
    priceCrowler: 14,
    priceGrowler: 20,
    colorLight: '#ff5',
    colorDark: '#fa0',
    abv: 7
  },{
    title: 'TLH',
    titleColor: '#4f4',
    style: 'Tallahassee Callsign Blonde Ale',
    description: '',
    price: 5,
    size: '16oz',
    price10oz: 0,
    price12oz: 4,
    price16oz: 5,
    priceCrowler: 10,
    priceGrowler: 16,
    colorLight: '#ff5',
    colorDark: '#fc5',
    abv: 5
  },{
    title: 'Advanced Darkness',
    titleColor: '#4f4',
    style: '2017 Gold Medal Robust Porter',
    description: '',
    price: 6,
    size: '16oz',
    price10oz: 0,
    price12oz: 5,
    price16oz: 6,
    priceCrowler: 12,
    priceGrowler: 19,
    colorLight: '#420',
    colorDark: '#2d0a00',
    abv: 6.6
  },{
      title: 'RVB',
    titleColor: '#fff',
    style: 'Raspberry Vanilla Brown',
    description: '',
    price: 5,
    size: '16oz',
    price10oz: 0,
    price12oz: 4,
    price16oz: 5,
    priceCrowler: 10,
    priceGrowler: 17,
    colorLight: '#DF7401',
    colorDark: '#8A2908',
    abv: 5.8
  },{
    title: 'To the Goal!',
    titleColor: '#fff',
    style: 'Tallahassee Soccer Club Session IPA',
    description: '',
    price: 6,
    size: '16oz',
    price10oz: 0,
    price12oz: 5,
    price16oz: 6,
    priceCrowler: 12,
    priceGrowler: 19,
    colorLight: '#FACC2E',
    colorDark: '#FFBF00',
    abv: 4.6
  },{
    title: 'LeBron Jamz',
    titleColor: '#fff',
    style: 'Blackberry/Raspberry-infused Sour',
    description: '',
    price: 6,
    size: '12oz',
    price10oz: 0,
    price12oz: 6,
    price16oz: 0,
    priceCrowler: 14,
    priceGrowler: 0,
    colorLight: '#FF0080',
    colorDark: '#FE2E9A',
    abv: 3.8
  },{
    title: 'Citrus Got Real',
    titleColor: '#fff',
    style: 'Tallahassee-sourced Meyer Lemon Sour',
    description: '',
    price: 6,
    size: '12oz',
    price10oz: 0,
    price12oz: 6,
    price16oz: 7,
    priceCrowler: 14,
    priceGrowler: 0,
    colorLight: '#FFFF00',
    colorDark: '#AEB404',
    abv: 3.5
  },{
    title: 'Donut Disco',
    titleColor: '#fff',
    style: '(Donut Kingdom) Stout w/cinnamon, coconut & vanilla',
    description: '',
    price: 8,
    size: '10oz',
    price10oz: 8,
    price12oz: 0,
    price16oz: 0,
    priceCrowler: 20,
    priceGrowler: 30,
    colorLight: '#210',
    colorDark: '#100',
    abv: 10.2
  },{
    title: 'Resilience',
    titleColor: '#fff',
    style: '(Sierra Nevada Brewing) Collab IPA',
    description: '',
    price: 6,
    size: '16oz',
    price10oz: 0,
    price12oz: 5,
    price16oz: 6,
    priceCrowler: 12,
    priceGrowler: 19,
    colorLight: '#f50',
    colorDark: '#c30',
    abv: 6.7
    },{
    title: '152 Mile Friendship',
    titleColor: '#fff',
    style: '(Cypress & Grove) Collab Tangerine Belgian Pale',
    description: '',
    price: 6,
    size: '16oz',
    price10oz: 0,
    price12oz: 5,
    price16oz: 6,
    priceCrowler: 12,
    priceGrowler: 19,
    colorLight: '#DF7401',
    colorDark: '#FF4000',
    abv: 6.1
  },{
    title: 'Sir Douglas Juicifer',
    titleColor: '#fff',
    style: 'New England-style Juicy Pale Ale',
    description: '',
    price: 7,
    size: '16oz',
    price10oz: 0,
    price12oz: 6,
    price16oz: 7,
    priceCrowler: 14,
    priceGrowler: 0,
    colorLight: '#F5DA81',
    colorDark: '#F7BE81',
    abv: 5.3
  }
]
